#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/config.env"
TOOLS="$SCRIPT_DIR/tools"
echo "A3D M1 Pro X1 configure v0.64.1"
if [[ -f "$OUT" ]]; then
  read -r -p "config.env exists. Overwrite? [y/N] " ans
  [[ "${ans,,}" == "y" ]] || exit 0
fi
prompt() { local v="$1" l="$2" s="${3:-0}" d="${4:-}"; local x; if [[ "$s" == "1" ]]; then read -r -s -p "$l: " x; echo ""; else read -r -p "$l [${d}]: " x; x="${x:-$d}"; fi; printf -v "$v" '%s' "$x"; }

echo "--- Release tarball (required for first build) ---"
prompt BUILD_ARTIFACTS_URL "BUILD_ARTIFACTS_URL (GitHub Releases tarball)" 0 ""

echo "--- WiFi (optional, blank = configure on device) ---"
prompt WIFI_SSID "WiFi SSID" 0 ""
prompt WIFI_PASSWORD "WiFi password" 0 ""
prompt WIFI_COUNTRY "Country" 0 "US"

echo "--- Accounts (for custom rebuilds; published image uses m1prox1/m1prox1) ---"
prompt ROOT_PASSWORD "root password" 1 "m1prox1"
prompt USER_NAME "User name" 0 "m1prox1"
prompt USER_PASSWORD "User password (blank=same as root)" 1 ""
USER_PASSWORD="${USER_PASSWORD:-$ROOT_PASSWORD}"
prompt USER_REALNAME "Full name" 0 "M1 Pro X1 Operator"
prompt LOCALE "Locale" 0 "en_US.UTF-8"
prompt TIMEZONE "Timezone" 0 "America/New_York"

echo "--- Optional paths ---"
prompt FACTORY_FIRMWARE_DIR "Factory 03_partitions dir (blank=use tarball)" 0 ""

read -r -p "Clone full Armbian/kernel git trees? (not needed for tarball rebuild) [y/N] " clone_src
FETCH_ARMBIAN_SOURCE="0"
FETCH_KERNEL_SOURCE="0"
if [[ "${clone_src,,}" == "y" ]]; then
  FETCH_ARMBIAN_SOURCE="1"
  FETCH_KERNEL_SOURCE="1"
  prompt BUILD_ARMBIAN_PATH "Armbian build clone path" 0 "$HOME/armbian-build"
  prompt KERNEL_SRC_PATH "Linux kernel clone path" 0 "$HOME/linux-v6.18"
else
  BUILD_ARMBIAN_PATH="${BUILD_ARMBIAN_PATH:-$HOME/armbian-build}"
  KERNEL_SRC_PATH="${KERNEL_SRC_PATH:-$HOME/linux-v6.18}"
fi

cat >"$OUT" <<EOF
# Generated by configure.sh - DO NOT COMMIT
BUILD_ARTIFACTS_URL="$BUILD_ARTIFACTS_URL"
FACTORY_FIRMWARE_DIR="$FACTORY_FIRMWARE_DIR"
FETCH_ARMBIAN_SOURCE="$FETCH_ARMBIAN_SOURCE"
FETCH_KERNEL_SOURCE="$FETCH_KERNEL_SOURCE"
BUILD_ARMBIAN_PATH="$BUILD_ARMBIAN_PATH"
KERNEL_SRC_PATH="$KERNEL_SRC_PATH"

WIFI_SSID="$WIFI_SSID"
WIFI_PASSWORD='$WIFI_PASSWORD'
WIFI_COUNTRY="$WIFI_COUNTRY"

ROOT_PASSWORD="$ROOT_PASSWORD"
USER_NAME="$USER_NAME"
USER_PASSWORD="$USER_PASSWORD"
USER_REALNAME="$USER_REALNAME"
LOCALE="$LOCALE"
TIMEZONE="$TIMEZONE"

SERIAL_GETTY="ttyFIQ0"
SERIAL_BAUD="1500000"

RELEASE="bookworm"
KERNEL_BRANCH="current"
UBOOT_DEFCONFIG="evb-rk3308_defconfig"
EOF
chmod 600 "$OUT"
echo "Wrote $OUT"

read -r -p "Download tarball and run preflight now? [Y/n] " fetch
if [[ "${fetch,,}" != "n" ]]; then
  bash "$TOOLS/fetch-build-sources.sh"
  bash "$TOOLS/preflight-v64.sh"
fi