#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$SCRIPT_DIR/config.env"
TOOLS="$SCRIPT_DIR/tools"
echo "A3D M1 Pro X1 configure v0.64.1"
if [[ -f "$OUT" ]]; then
  read -r -p "config.env exists. Overwrite? [y/N] " ans
  [[ "${ans,,}" == "y" ]] || exit 0
fi
prompt() { local v="$1" l="$2" s="${3:-0}" d="${4:-}"; local x; if [[ "$s" == "1" ]]; then read -r -s -p "$l: " x; echo ""; else read -r -p "$l [${d}]: " x; x="${x:-$d}"; fi; printf -v "$v" '%s' "$x"; }

prompt BUILD_SERVER_HOST "Build server IP (blank=local WSL)" ""
prompt BUILD_SERVER_USER "Build server SSH user" ""
BUILD_SERVER_PATH="/home/build/armbian-build"
BUILD_ARMBIAN_PATH="${BUILD_ARMBIAN_PATH:-$HOME/armbian-build}"
KERNEL_SRC_PATH="${KERNEL_SRC_PATH:-$HOME/linux-v13-build}"

echo "--- WiFi (optional) ---"
prompt WIFI_SSID "WiFi SSID" 0 ""
prompt WIFI_PASSWORD "WiFi password" 0 ""
prompt WIFI_COUNTRY "Country" 0 "US"

echo "--- Accounts (baked into image at build) ---"
prompt ROOT_PASSWORD "root password" 1 ""
prompt USER_NAME "User name" 0 "m1prox1"
prompt USER_PASSWORD "User password (blank=same as root)" 1 ""
USER_PASSWORD="${USER_PASSWORD:-$ROOT_PASSWORD}"
prompt USER_REALNAME "Full name" 0 "M1 Pro X1 Operator"
prompt LOCALE "Locale" 0 "en_US.UTF-8"
prompt TIMEZONE "Timezone" 0 "America/New_York"

echo "--- Source / factory paths (optional) ---"
prompt FACTORY_FIRMWARE_DIR "Factory 03_partitions dir (blank=skip)" 0 ""
prompt BUILD_ARTIFACTS_URL "URL to prebuilt releases tarball (blank=skip)" 0 ""
prompt BUILD_ARMBIAN_PATH "Armbian build clone path" 0 "$HOME/armbian-build"
prompt KERNEL_SRC_PATH "Linux kernel clone path" 0 "$HOME/linux-v13-build"

prompt SSH_PASSWORD "Build SSH password (optional)" 1 ""
prompt SUDO_PASSWORD "Build sudo password (optional)" 1 ""

cat >"$OUT" <<EOF
# Generated by configure.sh - DO NOT COMMIT
BUILD_SERVER_HOST="$BUILD_SERVER_HOST"
BUILD_SERVER_USER="$BUILD_SERVER_USER"
BUILD_SERVER_PATH="$BUILD_SERVER_PATH"
BUILD_ARMBIAN_PATH="$BUILD_ARMBIAN_PATH"
KERNEL_SRC_PATH="$KERNEL_SRC_PATH"
FACTORY_FIRMWARE_DIR="$FACTORY_FIRMWARE_DIR"
BUILD_ARTIFACTS_URL="$BUILD_ARTIFACTS_URL"
FETCH_ARMBIAN_SOURCE="1"
FETCH_KERNEL_SOURCE="1"

WIFI_SSID="$WIFI_SSID"
WIFI_PASSWORD='$WIFI_PASSWORD'
WIFI_COUNTRY="$WIFI_COUNTRY"

ROOT_PASSWORD="$ROOT_PASSWORD"
USER_NAME="$USER_NAME"
USER_PASSWORD="$USER_PASSWORD"
USER_REALNAME="$USER_REALNAME"
LOCALE="$LOCALE"
TIMEZONE="$TIMEZONE"

SERIAL_GETTY="ttyFIQ0"
SERIAL_BAUD="1500000"
SSH_PASSWORD="$SSH_PASSWORD"
SUDO_PASSWORD="$SUDO_PASSWORD"

RELEASE="bookworm"
KERNEL_BRANCH="current"
UBOOT_DEFCONFIG="evb-rk3308_defconfig"
GITHUB_REPO="https://github.com/xateesix/M1-SOC-Armbian-Build.git"
EOF
chmod 600 "$OUT"
echo "Wrote $OUT"

read -r -p "Install build dependencies and fetch source libraries now? [Y/n] " fetch
if [[ "${fetch,,}" != "n" ]]; then
  bash "$TOOLS/fetch-build-sources.sh"
fi
