#!/usr/bin/env bash
# Remove stale images and duplicate pack trees; keep rebuild essentials locally.
set -euo pipefail
ARMBIAN="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REL="$ARMBIAN/releases/1.0.0"

echo "=== RK3308BS workspace cleanup ==="
df -h /mnt/c 2>/dev/null | tail -1 || true

# WSL /tmp build debris
rm -rf /tmp/rk3308bs-v24-build /tmp/rootfs-*.img /tmp/test-v17.img /tmp/rf.img 2>/dev/null || true

# Duplicate factory / audit trees (rebuild from factory update img if needed)
rm -rf "$ARMBIAN/_factory_ref" "$ARMBIAN/_fixed_check" "$ARMBIAN/_v2_check" \
	"$ARMBIAN/factory_extract" "$ARMBIAN/factory_unpacked" \
	"$ARMBIAN/factory_fresh/01_update_img" "$ARMBIAN/factory_fresh/02_rkimagemaker" \
	"$ARMBIAN/factory_fresh/06_smoke_test" \
	"$ARMBIAN/KLP_IMG_ARTILLERY_M1_PRO_S1-SOC_20251126_Beta (1)" \
	"$ARMBIAN/KLP_IMG_ARTILLERY_M1_PRO_S1-SOC_20251126_Beta (1).zip" 2>/dev/null || true

[[ -d "$REL" ]] || { echo "No $REL  -  done"; exit 0; }

# Keep these local flash/build artifacts only
KEEP_FLASH=(
	rk3308bs-1.0.0-emmc-fixed-v21.img
	rk3308bs-1.0.0-emmc-fixed-v22.img
	rk3308bs-1.0.0-emmc-fixed.img
)
KEEP_ROOTFS=(rootfs-v11.img)

# Remove old flash images
shopt -s nullglob
for f in "$REL"/rk3308bs-*.img "$REL"/Armbian-*.img; do
	base=$(basename "$f")
	keep=0
	for k in "${KEEP_FLASH[@]}"; do [[ "$base" == "$k" ]] && keep=1; done
	[[ "$keep" -eq 1 ]] || { echo "rm flash: $base"; rm -f "$f"; }
done

# Remove intermediate rootfs copies
for f in "$REL"/rootfs*.img; do
	base=$(basename "$f")
	keep=0
	for k in "${KEEP_ROOTFS[@]}"; do [[ "$base" == "$k" ]] && keep=1; done
	[[ "$keep" -eq 1 ]] || { echo "rm rootfs: $base"; rm -f "$f"; }
done

# Pack staging duplicates (regenerated by stage-pack-v16.sh)
for d in "$REL"/pack_input_v*; do
	[[ -d "$d" ]] && { echo "rm -rf $(basename "$d")"; rm -rf "$d"; }
done

# Unpack/header scratch
rm -rf "$REL"/_hdr_v1 "$REL"/_hdr_v2 "$REL"/_unpack_v* 2>/dev/null || true

# Optional: drop full module tree if desperate for space (comment out to keep)
# rm -rf "$REL/_modules_6.18.0-dirty"

echo "=== After cleanup ==="
du -sh "$ARMBIAN" "$REL" 2>/dev/null | head -5
df -h /mnt/c 2>/dev/null | tail -1 || true
